library(RCOMPSs)
source("add3.R")
compss_start()
dec <- task(add_three, "add3.R", info_only = FALSE, return_value = TRUE)
res <- dec(5, 4)
res2 <- dec(5, 4)
res3 <- dec(res, res2)
res3 <- compss_wait_on(res3)
cat("The results is:", res3)
compss_stop()
