# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
rcpp_hello_world <- function() {
    .Call(`_RCOMPSs_rcpp_hello_world`)
}

#' Start a COMPSs-Runtime instance
#' @export
start_runtime <- function() {
    invisible(.Call(`_RCOMPSs_start_runtime`))
}

#' Start a COMPSs-Runtime instance
#' @export
stop_runtime <- function(code) {
    invisible(.Call(`_RCOMPSs_stop_runtime`, code))
}

#' Register a core element
#' @export
register_core_element <- function(CESignature, ImplSignature, ImplConstraints, ImplType, ImplLocal, ImplIO, prolog, epilog, container, typeArgs) {
    invisible(.Call(`_RCOMPSs_register_core_element`, CESignature, ImplSignature, ImplConstraints, ImplType, ImplLocal, ImplIO, prolog, epilog, container, typeArgs))
}

