# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Printout for debugging
#' @param str_to_print String to print if DEBUG_MODE is 1
NULL

#' Start a COMPSs-Runtime instance
#' @export
start_runtime <- function() {
    invisible(.Call(`_RCOMPSs_start_runtime`))
}

#' stop_runtime
#' 
#' Stop a COMPSs-Runtime instance
#' 
#' @param code The code to exit
#' @export
stop_runtime <- function(code) {
    invisible(.Call(`_RCOMPSs_stop_runtime`, code))
}

#' register_core_element
#' 
#' Register a core element
#'
#' @param CESignature String with the core element signature. Usually: module_file.module_name.task_name
#' @param ImplSignature String with the implementation signature. Usually: module_file.module_name.task_name
#' @param ImplConstraints String with the task constraints. Usually empty, but for example: computingUnits=1
#' @param ImplType String with the implementation type. Usually METHOD although there are others supported for binaries, etc.
#' @param ImplLocal String boolean indicating if the implementation has to be executed locally. Usually False.
#' @param ImplIO String boolean indicating if the implementation  has IO requirements. Usually False.
#' @param prolog String indicating any prolog action. Usually empty.
#' @param epilog String indicating any epilog action. Usually empty.
#' @param container String indicating if the task has to be executed within a container. Usually empty.
#' @param typeArgs String with all arguments (task parameters).
#' @export
register_core_element <- function(CESignature, ImplSignature, ImplConstraints, ImplType, ImplLocal, ImplIO, prolog, epilog, container, typeArgs) {
    invisible(.Call(`_RCOMPSs_register_core_element`, CESignature, ImplSignature, ImplConstraints, ImplType, ImplLocal, ImplIO, prolog, epilog, container, typeArgs))
}

#' process_task
#' 
#' Define the Rcpp function
#' 
#' @export
process_task <- function(app_id, signature, on_failure, time_out, priority, num_nodes, reduce, chunk_size, replicated, distributed, has_target, num_returns, values, names, compss_types, compss_directions, compss_streams, compss_prefixes, content_types, weights, keep_renames) {
    invisible(.Call(`_RCOMPSs_process_task`, app_id, signature, on_failure, time_out, priority, num_nodes, reduce, chunk_size, replicated, distributed, has_target, num_returns, values, names, compss_types, compss_directions, compss_streams, compss_prefixes, content_types, weights, keep_renames))
}

#' barrier
#' 
#' Halt all the tasks: Notify the runtime that our current application wants to "execute" a barrier. Program will be blocked in GS_BarrierNew until all running tasks have ended. Notifies the 'no more tasks' boolean value.
#' 
#' @export
barrier <- function(app_id, no_more_tasks) {
    invisible(.Call(`_RCOMPSs_barrier`, app_id, no_more_tasks))
}

